Отсутствие интернета (виджет) #10
MirrorsPhoto/electron pull request #32
Opened 2017-10-20 13:48 UTC by klimash

2017-10-20 15:19 UTC, jonkofee commented
Поверхностно поглядел, как-то кривовато работает

2017-10-20 15:20 UTC, klimash commented
что именно?)

2017-10-20 15:24 UTC, jonkofee commented
Пошел на роутере вытянул кабель, в приложении ничего не изменилось, подождал - тоже
Перезапустил приложение - ОК, отображает, что нет инет. Думаю, ну ок, пойду подключу кабель
Подключил, тоже ничего не изменилось, нажал на виджете товара сабмит и вуаля, показало, что подключение есть)

2017-10-21 16:34 UTC, jonkofee requested changes

2017-10-21 16:34 UTC, jonkofee commented on src/plugins/online.js
> +  const { get } = create({ timeout: 1000 })
Маленький таймаут, поставь хотяб 2 секунды

2017-10-21 16:34 UTC, jonkofee commented on src/plugins/online.js
> +      if (param === 'all') {
Обычно для таких случаев есть отдельный метод `removeAllListeners`

2017-10-21 16:34 UTC, jonkofee commented on src/store.js
> -    user: {},
Очень грязные коммиты получаются, тяжело их просматривать, т.к. вроде ты тут ничего не менял, чисто табуляция добавилась, а мне сиди и проверяй вдруг что-то еще))))
Если у тебя есть желание отформатировать код, то делай это отдельным пр, а тут только по делу

2017-10-21 16:38 UTC, jonkofee commented
Круто получилось
Теперь давай этот плагин вынесем отдельным npm пакетом, может еще кому полезен будет
Назови, к примеру, `check-internet-connection`

2017-10-22 12:29 UTC, klimash commented
@jonkofee дада, я собирался публиковать

2017-10-22 12:29 UTC, klimash commented on src/store.js
> -    user: {},
так и сделаю значит)

2017-10-22 12:30 UTC, klimash commented on src/plugins/online.js
> +  const { get } = create({ timeout: 1000 })
секунды хватает чтобы понять есть интернет или нет

2017-10-22 12:31 UTC, klimash commented on src/plugins/online.js
> +      if (param === 'all') {
ну у меня вот такой самобытный стиль) сделаю отельным

2017-10-23 07:43 UTC, jonkofee commented
В пакет будешь выносить?

2017-10-23 07:44 UTC, klimash commented
@jonkofee да, позже чутка

2017-10-25 12:45 UTC, jonkofee approved these changes

2017-10-25 12:45 UTC, merged