Autoupdate refactoring #17
MirrorsPhoto/electron pull request #36
Opened 2017-10-23 12:30 UTC by klimash

2017-10-23 12:45 UTC, jonkofee requested changes

2017-10-23 12:45 UTC, jonkofee commented on src/components/UI/updateModal.vue
> +  mounted() {
не обрабатываешь `au-error`

2017-10-23 12:45 UTC, jonkofee commented
<img width="1792" alt="screen shot 2017-10-23 at 15 44 14" src="https://user-images.githubusercontent.com/9060043/31889634-2f7f54f2-b809-11e7-98a9-cab872ac1dd5.png">
Сделай, чтобы одна полоса прокрутки была

2017-10-23 12:48 UTC, jonkofee commented
Шаблон релиз нотов:
### Исправления
- Правильное склонения количества клиентов
- Правильный курсор на кнопках
- Из svg убраны тайтлы
- Обработка ошибки **401**. Теперь при возникновении ошибки с токеном - приложение переводит на страницу авторизации
### Новый функционал
- Виджеты
  - Фото
  - Товары
  - Ксерокопия
  - Ламинация
- Чек
- Кнопки управления окном
  - Свернуть
  - Закрыть
  - Во весь экран
- Запрет на выделение текста
- Соединение с Photoshop по WebSocket

Стилизуй эти точечки красиво

2017-10-23 12:52 UTC, jonkofee requested changes

2017-10-23 12:52 UTC, jonkofee commented on src/components/UI/updateModal.vue
> +      this.$electron.ipcRenderer.send('au-download-confirm')
И закрыть модалку

2017-10-23 12:55 UTC, jonkofee requested changes

2017-10-23 12:55 UTC, jonkofee commented on src/components/UI/updateModal.vue
> +          <h3>История изменений:</h3>
Это не история изменений, а "что нового"

2017-10-23 12:56 UTC, jonkofee commented on src/components/UI/updateModal.vue
> +          <h3>История изменений:</h3>
"История изменений" это вообще вся вся история, с самой первой версии и до последней. А нас интересует именно "что нового", т.е. с текущей версии и до последней. Не нужно их разбивать на разные группы

2017-10-23 15:22 UTC, klimash commented on src/components/UI/updateModal.vue
> +          <h3>История изменений:</h3>
что нового это в последней версии. а тут история всех версий

2017-10-24 09:42 UTC, jonkofee commented on src/components/UI/updateModal.vue
> +          <h3>История изменений:</h3>
Нет. Нам не нужна история всех версий

2017-10-25 08:27 UTC, jonkofee commented
Сериализованный объект
```
{"version":"0.5.0","releaseDate":"2017-10-20T07:03:11.825Z","path":"Mirror's Photo-0.5.0-mac.zip","sha512":"P+8E3q5AWzfMfUyF+VwbHRIQJrWGF3WgEFdU406FURlU+ZgsCBvrlJj3ifO9ywPI32ZBVDIx3FCyiN6O1183mw==","githubArtifactName":"Mirrors-0.5.0-mac.zip","releaseName":"0.5.0","releaseNotes":[{"version":"0.5.0","note":"<h3>Исправления</h3>\n<ul>\n<li>Правильное склонения количества клиентов</li>\n<li>Правильный курсор на кнопках</li>\n<li>Из svg убраны тайтлы</li>\n<li>Обработка ошибки <strong>401</strong>. Теперь при возникновении ошибки с токеном - приложение переводит на страницу авторизации</li>\n</ul>\n<h3>Новый функционал</h3>\n<ul>\n<li>Виджеты\n<ul>\n<li>Фото</li>\n<li>Товары</li>\n<li>Ксерокопия</li>\n<li>Ламинация</li>\n</ul>\n</li>\n<li>Чек</li>\n<li>Кнопки управления окном\n<ul>\n<li>Свернуть</li>\n<li>Закрыть</li>\n<li>Во весь экран</li>\n</ul>\n</li>\n<li>Запрет на выделение текста</li>\n<li>Соединение с Photoshop по WebSocket</li>\n</ul>"},{"version":"0.4.0","note":"<h3>Исправления</h3>\n<ul>\n<li>Шрифт в виджете стал немного тоньше</li>\n</ul>\n<h3>Новый функционал</h3>\n<ul>\n<li>Новый шрифт San Francisco</li>\n</ul>"},{"version":"0.3.0","note":"<h3>Исправления</h3>\n<ul>\n<li>Изменена иконка</li>\n</ul>\n<h3>Новый функционал</h3>\n<ul>\n<li>Реализованы виджеты\n<ul>\n<li>Погода</li>\n<li>Время</li>\n<li>Касса</li>\n<li>Количество клиентов</li>\n</ul>\n</li>\n</ul>"}]}
```

2017-10-25 10:22 UTC, jonkofee commented
😔
<img width="1792" alt="screen shot 2017-10-25 at 11 16 27" src="https://user-images.githubusercontent.com/9060043/31993946-87699608-b987-11e7-88b8-7f0684911f29.png">

2017-10-25 12:22 UTC, jonkofee requested changes

2017-10-25 12:22 UTC, jonkofee commented on src/App.vue
> +.release_info ul
Почему тут, а не в компоненте модалки?

2017-10-25 12:53 UTC, klimash commented on src/App.vue
> +.release_info ul
он применяет стили к заранее прописанным тегам. а эти вставляются через v-html. и стили в итоге не срабатывают.

2017-10-25 14:37 UTC, jonkofee approved these changes

2017-10-25 14:38 UTC, merged